remote_theme: pages-themes/cayman@v0.2.0
title: "CS4641: Intro To Machine Learning" 
github:
  is_project_page: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one